<!doctype html public "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
<title>Advanced Exception Handling</title>
<script type="text/javascript" src="scripts/header.js"></script>
<link rel="stylesheet" type="text/css" href="css/prog.css">

</head>

<body onload='window.focus()'>
<h2 style="padding-left: 30px;">Advanced Exception Handling</h2>
<h3>Topics Covered:</h3>
<ul>
<li>What are Exceptions?</li>
<li>Review of Exception Handling</li>
<li>Checked and Unchecked Exceptions</li>
<li>More Advanced Exception Handling</li>
<ul>
<li>Exceptions and the Call Stack</li>
<li>Multiple Catch-Blocks</li>
<li>The throws Statement</li>
</ul>
<li>When to use Exception Handlers</li>
</ul>
<h3>Things To Do Before Reading This Section:</h3>
<ul>
<li>Get the Presentation file for this lesson</li>
<li>Read all of Chapter 13</li>
<li>Browse through the tutorial Handling Errors Using Exceptions at java.sun.com.</li>
<li>Read the following articles and tutorials:</li>
<ul>
<li>JavaWorld: Exceptions in Java</li>
<li>The Essence of OOP using Java, Exception Handling</li>
<li>Unchecked Exceptions: The Controversy</li>
<li>Checked or Unchecked Exceptions?</li>
</ul>
</ul>
<h3>What are Exceptions</h3>
<h4>First, read Section 13.1, 13.2, and 13.3 in your textbook, and re-read section 2.17.</h4>
<p>After doing the required readings, you should be familiar with the following terms and concepts:</p>
<ul>
<li>What an "Exception" is.</li>
<li>The try-catch block</li>
<li>Catch-block parameter</li>
<li>The throw statement.</li>
<li>Throwing an exception; handling an exception.</li>
<li>What's a huge advantage of using exception handling?</li>
</ul>
<p>There are three categories of errors in programming (these are covered in Chapter 2.17 of your textbook):</p>
<ul>
<li><strong>Compile-time Errors</strong> (or just "Compile/Compilation Errors")</li>
<ul>
<li>Errors that are caught by the compiler when you build your source code.</li>
<li>Also often referred to as syntax errors because they usually involve incorrect syntax.</li>
</ul>
<li><strong>Run-time Errors</strong> (or Execution Errors)</li>
<ul>
<li>Errors that occur while a program is running.</li>
<li>Usually they cause the program to "crash".</li>
</ul>
<li><strong>Logic Errors</strong></li>
<ul>
<li>Errors in the logic of the program.</li>
<li>These kinds of errors don't yield error messages.</li>
<li>Usually they cause things like endless loops, by-passed code, incorrect output, etc.</li>
</ul>
</ul>
<h5>Stylistic errors and mistakes or omissions in adhering to programming standards are not considered in any of the above categories.</h5>
<p><strong>Exceptions</strong> are error conditions or exceptional circumstances that occur in a program, and they usually fall into the category of <strong>Compilation Errors</strong>. For example, you might ask the user to enter a number but instead, they enter a string. Sometimes exceptions occur in a program because you've written some code incorrectly, for example you might get a NullPointerException if you declare an object variable and then try to invoke one of the object's methods before you actually instantiate the object, or you might get a ClassCastException if you try to make an illegal explicit cast of an object. As programmers, we need to think more about the exceptions that could be caused by the user, such invalid user-entered data. We don't want our programs to crash just because the user entered the wrong data, so we need to think about and account for these kinds of errors.</p>
<p>When an error occurs in a running program, we say that "<strong>an exception is thrown</strong>". An Exception is actually an object, and when an error occurs, the appropriate exception class is instantiated and thrown by the statement that caused the exception. We say that a program "<strong>catches</strong>" or handles the exception. This could mean that you write code that prompts the user to enter a different value until they get it right.</p>
<p>There are a variety of Exception classes in the Java language, and many are part of the java.lang package. These classes are categorized in a hierarchy where the generic Throwable class is at the top. The Throwable class models any error or exception object that can be thrown. Exception classes get more specific as you get down the hierarchy.</p>
<h4>Learn more: &nbsp;</h4>
<h5>JavaWorld: Exceptions in Java &nbsp;</h5>
<h5>The Essence of OOP using Java, Exception Handling</h5>
<h3>Review Exception Handling</h3>
<p>We keep talking about code that "handles the exception" -- what does this mean exactly? When an exception is thrown by a statement in a program, there should be additional statements in your code that "catch" or handle the exception. For example, you might say that if an IOException occurs when you try to read a line of data from a file, handle the exception by displaying a message to the user and closing the file.</p>
<p>The code structure used to handle exceptions is the try/catch block:</p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">try {&nbsp;&nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">// try this code that does something </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">} catch (Exception ex) { &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">// if the code in the try block throws an exception &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">// then stop what you're doing and run this code &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">// (ex is the exception object that was thrown) </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">}</span></p>
<p>If there is a piece of code that might throw an exception, you would put it in the try-block. Notice that this is indeed a block of code, so if you declare any variables in the try-block, they are local to that block!</p>
<p>If an exception is thrown from inside the try-block, the flow of control jumps immediately to the catch-block. Notice the parameter in the catch-block: even though the catch-block is not a method, it does require the Exception parameter. This Exception object variable (here it's called ex) contains a reference to the Exception object that was generated and thrown. In the catch-block, you can include code that handles the error. Having access to the exception object might be useful if you need to examine the exception. For example, you can see what value caused the exception, if applicable, or you can print a stack trace, which is a list of the different method calls and statements that led to the error.</p>
<h4>Example</h4>
<p>Write a program that asks the user for a numeric value, parses it into an integer, and then prints the square of that number on the console:</p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">// sample program for </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">// testing exceptions import javax.swing.*;</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">public class TestingExceptions { &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">public static void main(String[] args) &nbsp;{ &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">int num = Integer.parseInt(JOptionPane.showInputDialog(null,&nbsp;"Enter a whole number greater than 0.", "Number", &nbsp;&nbsp;&nbsp;JOptionPane.QUESTION_MESSAGE));</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">JOptionPane.showMessageDialog(null, &nbsp;&nbsp;&nbsp;"The square of your number is " + Math.pow(num, 2), &nbsp;&nbsp;&nbsp;"Square", JOptionPane.INFORMATION_MESSAGE); &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">}</span></p>
<p>Run your program and test it with a valid number. Then run your program and test it with an invalid number, such as the value "hi". What exception message do you get?</p>
<p>The output you will see is what's called the <strong>stack trace</strong>:</p>
<p style="padding-left: 30px;"><strong>Exception in thread "main" java.lang.NumberFormatException: For input string: "hi" at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong></p>
<p style="padding-left: 30px;"><strong>at java.lang.Integer.parseInt(Integer.java:447) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong></p>
<p style="padding-left: 30px;"><strong>at java.lang.Integer.parseInt(Integer.java:497) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong></p>
<p style="padding-left: 30px;"><strong>at TestingExceptions.main(TestingExceptions.java:16)</strong></p>
<p style="padding-left: 30px;"><strong>Press any key to continue...</strong></p>
<p>The first line indicates that a NumberFormatException was thrown, and the value in question was "hi". At the bottom of the stack trace, you'll see the line number and the program name where the problem started. In this case it was in TestingExceptions main() method on line 16, which in my program was the line that called parseInt(). You can also see where in the Integer class code the error occured: On executing line 16 of my program, it executed some method call on line 497 of the Integer class, which eventually caused a problem on line 447.</p>
<p>Our program compiled okay because NumberFormatException is an unchecked exception. Even though all the parse methods could throw it, you are not required to handle it. However, sometimes you might want to do so, in case the user enters an invalid number.</p>
<p>To handle the exception, we can use a try-catch block: if the value is invalid, display an error message. What code should go in the try-block; which code will possibly generate the error? This would be the parseInt() method, so we need to make sure that statement goes in the try-block. Where should our statement that prints the square go? Whether an exception is thrown or not, any code after the catch block will always be executed, so we don't want this statement after the catch. If an error occurs, program flow moves to the catch-block and the rest of the code in the try-block is ignored. Therefore, it's a good idea to put the calculation after the parseInt() method -- it will only execute if no error occurs!</p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">public static void main(String[] args) { &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">try &nbsp;{ &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">int num = Integer.parseInt(JOptionPane.showInputDialog(null, &nbsp;&nbsp;&nbsp;"Enter a whole number greater than 0.", "Number", &nbsp;&nbsp;&nbsp;JOptionPane.QUESTION_MESSAGE));</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">JOptionPane.showMessageDialog(null, &nbsp;&nbsp;&nbsp;"The square of your number is " + Math.pow(num, 2), &nbsp;&nbsp;&nbsp;"Square", JOptionPane.INFORMATION_MESSAGE); &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} &nbsp;catch (Exception ex) &nbsp;{ &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">JOptionPane.showMessageDialog(null, &nbsp;&nbsp;&nbsp;"An error occured when you entered a number!", &nbsp;&nbsp;&nbsp;"Error", JOptionPane.ERROR_MESSAGE); &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">}</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">}</span></p>
<p>&nbsp;Modify your code so that the value of the call to ex.getMessage() appears in the dialog box. What is displayed? What if you change it to ex.toString()?</p>
<h3>Checked vs. Unchecked Exceptions</h3>
<h4>First, read chapter 13.4.</h4>
<p>In Chapter 13.4, Figure 13.1 shows a diagram of part of the exception class hierarchy. After reading this section and examining this diagram, you should become familiar with the following terms and concepts:</p>
<ul>
<li>The Throwable, Exception, and RuntimeException classes.</li>
<li>System errors, the Error class.</li>
<li>Examples of problems that might cause an Error to be thrown.</li>
<li>Examples of checked exceptions.</li>
<li>Examples of unchecked exceptions.</li>
<li>What's the main difference between checked exceptions and unchecked exceptions?</li>
</ul>
<p>You can break the types of errors or exceptions into two categories: <strong>checked exceptions</strong> and <strong>unchecked exceptions</strong>. Checked exceptions MUST be handled in your code before you compile your program. For example, there are certain methods that will throw exception objects in certain circumstances. For example, the readLine() method of the BufferedReader class, which is used to read in a line of data from an input source, will throw an IOException if there is a problem accessing the file. IOException is a checked exception, so you will receive a compile error if you try to compile a program using BufferedReader.readLine() without accounting for this exception. Even if you are going to use the program yourself and know that you won't cause an error, you still must handle this exception, just in case it occurs.</p>
<p>Unchecked exceptions either can't be handled by the programmer (as in the case of exceptions that are descended from the Error class), or the programmer is not required to handle them (as in the case of exceptions that are descended from RuntimeException) -- you can compile the code without handling unchecked exceptions (although in many cases it isn't wise to ignore these, either).</p>
<p>How do you know which exceptions are checked and which are unchecked? You'll notice in the diagram that the Throwable class not only has a child class called Exception, which has a child class called RuntimeException, but there is also a child class called Error.</p>
<p><strong>The Error class</strong> represents errors that occur in the JVM. For example, the JVM might inexplicably stop working, or it might run out of memory. These are errors that the programmer has very little, if any, control over. These are unchecked exceptions: the programmer can't handle or isn't required to handle these kinds of errors in the program. We will not be focusing on members of this class in this course.</p>
<p><strong>The Exception class</strong> contains a wide variety of child classes, one of which is the RuntimeException class. The RuntimeException class also contains unchecked exceptions. These include NumberFormatException (which occurs if you try to execute Integer.parseInt() on a string value, for example), and ArrayIndexOutOfBoundsException (which occurs if you try to access an array element that it out of the array's defined boundaries). You don't have to handle these exceptions in order for your program to compile because they usually have something to do with programmer error. For example, if you don't check that a value is a valid numeric before you parse it into an int or a double, or if you don't make sure an array index is valid, exceptions could be thrown. However, you are not required to handle them. In fact, it is considered extremely inefficient to write exception handlers for unchecked exceptions; it is much better to write logic to avoid them (such as if-statements).</p>
<p>All exception classes that are descended from Exception but not descendants of RuntimeException are checked exceptions: you must make sure you handle these exceptions in your code or your program won't compile.</p>
<h4>Exercise</h4>
<p>You should already be familiar with a number of exceptions from your own programming experience so far. Which of the exceptions below are unchecked exceptions and which are checked exceptions? Under what circumstances is each exception thrown?</p>
<ol>
<li>NullPointerException</li>
<li>ArrayIndexOutOfBoundsException</li>
<li>NumberFormatException</li>
<li>IllegalArgumentException</li>
<li>ClassNotFoundException</li>
</ol>
<h3>More Advanced Exception Handling</h3>
<h4>First, read Chapter 13.5.</h4>
<p>After reading Chapter 13.5, you should be familiar with the following terms and concepts:</p>
<ul>
<li>declaring or claiming an exception</li>
<li>catching an exception</li>
<li>throwing an exception</li>
<li>throwing exceptions in methods, the call stack</li>
</ul>
<h4>Exceptions and the Call Stack</h4>
<p>As explained in Chapter 13.5, a catch-block is skipped over if no exceptions occur in the try-block. However, if an exception occurs in a try-block, program control moves to the catch-block. If an exception occurs in a piece of code that isn't inside a try-block, the exception will travel back up the call stack until it either finds the right catch-block. If no catch block is found, the program terminates and the exception's stack trace is displayed on the screen.</p>
<p>See the description on pages 440-41 and Figure 13.3 for a fuller explanation of this concept.</p>
<p>Here is a simple example:</p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">01: public static void main(String[] args) {</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">02: &nbsp;&nbsp;&nbsp; try {</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">03: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Scanner fileIn = getScanner();</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">04: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if (fileIn != null) {</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">05: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; System.out.println(getFileContents(fileIn));</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">06: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; }</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">07: &nbsp;&nbsp;&nbsp; } catch (Exception ex) {</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">08: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; System.out.println("A fatal error occured.");</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">09: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ex.printStackTrace();</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">10: &nbsp;&nbsp;&nbsp; }</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">11: }</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">12: </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">13: public static Scanner getScanner() throws FileNotFoundException {</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">14: &nbsp;&nbsp;&nbsp; Scanner in = null;</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">15: &nbsp;&nbsp;&nbsp; String fileName = JOptionPane.showInputDialog(null,</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">16: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "Enter the name of the file you'd like to view.",</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">17: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "View Grades File", JOptionPane.INFORMATION_MESSAGE);</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">18: &nbsp;&nbsp;&nbsp; if (fileName != null &amp;&amp; !fileName.equals("")) {</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">19: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; in = new Scanner(new File(fileName));</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">20: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; in.useDelimiter(System.getProperty("line.separator"));</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">21: &nbsp;&nbsp;&nbsp; }</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">22: &nbsp;&nbsp;&nbsp; return in;</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">23: }</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">24: </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">25: public static String getFileContents(Scanner in) {</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">26: &nbsp;&nbsp;&nbsp; String s = "";</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">27: &nbsp;&nbsp;&nbsp; while (in.hasNext()) {</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">28: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; String record = in.next();</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">29: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Scanner lineIn = new Scanner(record);</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">30: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; lineIn.useDelimiter("\\|");</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">31: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; String course = lineIn.next();</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">32: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; String title =&nbsp; lineIn.next();</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">33: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; double grade = lineIn.nextDouble();</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">34: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; double outOf = lineIn.nextDouble();</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">35: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; double weight = lineIn.nextDouble();</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">36: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; s += String.format("%-10s %-20s: %.1f/%.1f (%.1f%%)%n", course, title,</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">37: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; grade, outOf, weight);</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">38: &nbsp;&nbsp;&nbsp; }</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">39: &nbsp;&nbsp;&nbsp; return s;</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">40: }</span></p>
<p>In the above example, if you enter the name of a file in the dialog box that doesn't exist (in my example, I typed "blah.dat") in the project's root directory, a FileNotFoundException will occur on the statement in = new Scanner(new File(fileName)); on line 19 in the getScanner() method. When this happens, the program flow stops and control goes back to the calling method (the method that called getScanner(), which in this case is the main() method) on line 3.</p>
<p>From line 3, program control jumps to the catch-block, which starts on line 7. Then the two statements in the catch block execute, which causes the following output to appear:</p>
<p style="padding-left: 30px;"><strong>run: A fatal error occured. java.io.FileNotFoundException: blah.dat (The system cannot find the file specified) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong></p>
<p style="padding-left: 30px;"><strong>at java.io.FileInputStream.open(Native Method) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong></p>
<p style="padding-left: 30px;"><strong>at java.io.FileInputStream.&lt;init&gt;(FileInputStream.java:106) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong></p>
<p style="padding-left: 30px;"><strong>at java.util.Scanner.&lt;init&gt;(Scanner.java:636) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong></p>
<p style="padding-left: 30px;"><strong>at prog24178.exceptions.Main.getScanner(Main.java:45) &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </strong></p>
<p style="padding-left: 30px;"><strong>at prog24178.exceptions.Main.main(Main.java:29) </strong></p>
<p style="padding-left: 30px;"><strong>BUILD SUCCESSFUL (total time: 4 seconds)</strong></p>
<p>&nbsp;Similarly, if an error occurs in the getFileContents() method (e.g. if the file does not use the proper delimiter (NoSuchElementException), if the values assumed to be doubles contain invalid characters (InputMismatchException)) then program control goes back to line 5 in the main() method, and then jumps to the catch-block.</p>
<h4>Multiple Catch Blocks</h4>
<p>What if you had two different kinds of exceptions that you wanted to catch, and you had different code to execute for each? For example, what if the user doesn't enter a command-line argument when they run the program? We might like to display a different error message. This is a different action than the one we take if the user enters an invalid number, so do we write the program to perform two different error-handling tasks?</p>
<h4>Exercise</h4>
<ol>
<li>Write a program that does the following: (i) declares an array of 10 doubles (ii) fills the array with the roots from 1 to 10 (i.e. element 2 contains the root of 3)&nbsp;(iii) prompts the user to enter a number from 1 to 10 (iv) looks up and displays the root of that number from the array</li>
<li>What exceptions could possibly be thrown in this program? You should guess that an exception could be thrown if the user enters an invalid index value (less than 1 or greater than 10), or if they enter an index that's not a valid numeric (i.e. the value "two").</li>
<li>What's the name of the exception object that is generated when the user enters an invalid index?</li>
</ol>
<p>Let's say that if the user enters an invalid numeric value or an invalid index, we'll prompt them until they get it right. However, we want two different error messages to be displayed with different instructions. How can we do this?</p>
<p>You can perform different tasks for different exceptions by using more than one catch block. We can add one catch block to show the invalid index message and we can add a second catch block to show the invalid numeric message. Modify your program to include a loop that continues as long as the index is invalid. You can initialize index to a value like -1, and then continue the loop as long as index stays at -1. Make sure you keep this in mind when writing your catch blocks!</p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">import javax.swing.*;</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">public class MultiExceptions {&nbsp;&nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">public static void main(String[] args) &nbsp;{&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">double[] nums = new double[10];&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">for (int i=0; i&lt;nums.length; i++)&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">nums[i] = Math.sqrt(i+1);&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">int index = -1;&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">while (index &lt; 0) &nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">try &nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 150px;"><span style="font-family: courier new,courier;">index = Integer.parseInt(JOptionPane.showInputDialog(null, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Enter a number from 1 to 10.", "Enter Index", &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;JOptionPane.QUESTION_MESSAGE));&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 150px;"><span style="font-family: courier new,courier;">JOptionPane.showMessageDialog(null, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"The root of " + index + " is " + nums[index-1], &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Root", JOptionPane.INFORMATION_MESSAGE);</span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">}&nbsp;catch (NumberFormatException ex) &nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 150px;"><span style="font-family: courier new,courier;">JOptionPane.showMessageDialog(null, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"You entered something that isn't a valid number.&nbsp; Please try again.", &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Error", JOptionPane.ERROR_MESSAGE);&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">} &nbsp;&nbsp;&nbsp;catch (ArrayIndexOutOfBoundsException ex) &nbsp;&nbsp;&nbsp;{&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 150px;"><span style="font-family: courier new,courier;">JOptionPane.showMessageDialog(null, &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;index + " is not valid.&nbsp; Please enter a value from " + &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"1 to 10.", "Error", JOptionPane.ERROR_MESSAGE);&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 150px;"><span style="font-family: courier new,courier;">index = -1;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">}&nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">}</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">} </span></p>
<p><span style="font-family: verdana,geneva;">One thing to be careful of when working with multiple catch blocks is when you are catching more generic exception classes. For example, try compiling the following program: \</span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">public static void main(String[] args) {&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">String fileName = "";&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">Scanner fileIn;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">Scanner keysIn = new Scanner(System.in);</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">while (fileName.equals("")) {&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">try { </span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">System.out.print("Enter the name of the file: ");&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">fileName = keysIn.nextLine();</span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">fileIn = new Scanner(new File(fileName));&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">fileIn.useDelimiter(System.getProperty("line.separator"));</span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">int numRecords = 0;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">while(fileIn.hasNext()) {&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 150px;"><span style="font-family: courier new,courier;">fileIn.next();&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 150px;"><span style="font-family: courier new,courier;">numRecords++;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">}</span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">fileIn.close();&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">System.out.println("Number of records in file " + fileName + ": " + numRecords);</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">} catch (IOException ex) {&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">System.out.println("An input/output error occurred.&nbsp; Stack trace: ");&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">ex.printStackTrace();&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">System.out.println("\nTerminating program.");&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">} catch (FileNotFoundException ex) {&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">System.out.println("The file " + fileName + " does not exist or is invalid.&nbsp; Try again.");&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">fileName = "";&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">}&nbsp;&nbsp;&nbsp;&nbsp; </span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">}</span></p>
<p>&nbsp;What happens when you compile this code? The error message says that "exception java.io.FileNotFoundException has already been caught". What does this mean? If you recall, a class like FileNotFoundException is descended from the IOException class. In other words, FileNotFoundException is a child of IOException. When one class is a child of another, Java can implicitly cast the child class into a variable of the same type as the parent. A FileNotFoundException object is also an IOException object. Java is saying that because we put the catch for IOException first, this will catch any IOException object, plus any other object that comes from a child class of IOException! In effect, the first catch block will catch both exceptions!</p>
<p>This is a problem, because we have two different actions for each exception. The solution is to put IOException AFTER FileNotFoundException. In fact, this is a rule: with multiple catch blocks, always put the most specific classes or the child classes first!</p>
<p>In our first multiple exceptions example with NumberFormatException and ArrayIndexOutOfBoundsException it doesn't matter, because both are child classes of RunTimeException so they're on the same level.</p>
<h4>Using the instanceof Operator</h4>
<p>Another way to handle multiple exceptions is to have one catch block for a more generic exception class and then use an if statement to see which exception occurred. This would suit our first multiple-catch block exercise because there is a bit of redundance in our code. For example, we could have:</p>
<p style="padding-left: 30px;"><strong>Catch block: </strong></p>
<p style="padding-left: 30px;"><strong>If a FileNotFoundException occurred &nbsp;</strong></p>
<p style="padding-left: 60px;"><strong>[display error message for file-not-found] </strong></p>
<p style="padding-left: 30px;"><strong>Else If an IOException occurred &nbsp;</strong></p>
<p style="padding-left: 60px;"><strong>[display generic i/o error message] </strong></p>
<p style="padding-left: 30px;"><strong>End If</strong></p>
<p>How do we know which exception occurred? The instanceof operator will test an object to see what class it belongs to. For example:</p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">if (ex instanceof FileNotFoundException) {</span></p>
<p>&nbsp;..will return true if the ex object is a FileNotFoundException.</p>
<h3>The throws Statement</h3>
<p>Sometimes you'll have some methods that you feel should include a try/catch block for error handling. Or you might find that you've got a couple of try/catch blocks with very similar code for different exception classes. In addition, good class design might dictate that a method not handle it's own exceptions; you usually would have a centralized error handler that takes care of all the errors in a program.</p>
<p>You can "pass the buck", as they say: You can tell a method that if any exceptions occur, don't handle them, just pass them up to the calling program. For example, say you have a main() method that invokes a method someMethodName(). You can tell someMethodName() to pass any exceptions up to be handled in the main() method. This is done using the throws statement.</p>
<h4>Example</h4>
<p>Start off by writing a simple program with the following specs:</p>
<ul>
<li>Three private static methods getHours(), getMinutes(), and getSeconds() each take in a time string and return an int. Each method retrieves the value for hours, minutes, or seconds as appropriate.</li>
<li>A private static method getTotalSeconds() that takes a time string and returns an int value representing the total number of seconds in that time. This is calculated by retrieving the int value for hours, the int value for minutes, and the int value for seconds and using these in a formula to calculate the total number of seconds.</li>
<li>The main method takes a single command-line argument and passes it into the getTotalSeconds() method. The result of getTotalSeconds() is displayed on the screen.</li>
</ul>
<p>The main method code would be:</p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">public static void main(String[] args) {&nbsp;&nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">String time = JOptionPane.showInputDialog(null, &nbsp;&nbsp;"Enter a time in the format hh:mm:ss", "Enter Time", &nbsp;&nbsp;JOptionPane.QUESTION_MESSAGE);&nbsp;&nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">int totalSeconds = getTotalSeconds(time);&nbsp;&nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">JOptionPane.showMessageDialog(null, totalSeconds, "Total Seconds", &nbsp;&nbsp;JOptionPane.INFORMATION_MESSAGE); </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">} </span></p>
<p><span style="font-family: verdana,geneva;">What exceptions do you anticipate just with the main method?</span></p>
<p>Write the four methods described above. What kinds of exceptions do you anticipate these methods might cause? Try running your program with valid data to make sure it works, then try running it with invalid data to see what kinds of exceptions occur.</p>
<p>When finished, your program should look similar to the following:</p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">public class UsingThrows { &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">public static void main(String[] args) &nbsp;{ &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">String time = JOptionPane.showInputDialog(null, &nbsp;&nbsp;&nbsp;"Enter a time in the format hh:mm:ss", "Enter Time", &nbsp;&nbsp;&nbsp;JOptionPane.QUESTION_MESSAGE); &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">int totalSeconds = getTotalSeconds(time); &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">JOptionPane.showMessageDialog(null, totalSeconds, "Total Seconds", &nbsp;&nbsp;&nbsp;JOptionPane.INFORMATION_MESSAGE); &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} &nbsp; &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">private static int getTotalSeconds(String t) &nbsp;{ &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">return getHours(t) * 3600 + getMinutes(t) * 60 + getSeconds(t); &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">private static int getHours(String t) &nbsp;{ &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">return Integer.parseInt(t.substring(0, t.indexOf(":"))); &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">private static int getMinutes(String t) &nbsp;{ &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">return Integer.parseInt(t.substring(t.indexOf(":") + 1, t.lastIndexOf(":"))); &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">private static int getSeconds(String t) &nbsp;{ &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">return Integer.parseInt(t.substring(t.lastIndexOf(":")+1)); &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">}</span></p>
<p>In testing your program you probably noticed that you get a StringIndexOutOfBoundsException when the time string is missing one or both of the colons. In this case, the indexOf() method returns a -1, which is an invalid index value for the substring() method. You'll also find that if you enter a value of strings with colons (e.g. "hi:hi:hi"), you'll get a NumberFormatException when the parseInt() method tries to parse the string "hi" that was retrieved using substring/indexOf.</p>
<p>These two problems occur in all three of the getmethods. We could include a try/catch block in each of the three methods, but we would probably find that the code would be exactly the same. For example, getHours() might have:</p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">try { &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">int h = t.substring(0, t.indexOf(":")); </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">} catch (Exception ex) { &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">System.out.println("Invalid time!"); </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">}</span></p>
<p>The code for the getMinutes() and getSeconds() will be almost exactly the same! It seems redundant to type the try/catch block three times. Having so many try/catch blocks will make the code look cluttered and hard to read, and will result in a lot of unnecesary repetition.</p>
<p>The solution to this problem is to tell each of the get methods that, if an exception occurs, toss it up to the main method. That way, we could have one try/catch block in main() to handle all the errors. Since the get methods are called by getTotalSeconds(), we'll also have to tell getTotalSeconds() to pass to main() any errors it receives from the other three methods.</p>
<p>We accomplish this using the throws statement (not "throw" - that's different!). This statement goes at the end of the method signature and indicates that this method is going to throw back exceptions to the calling program:</p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">private static int getHours(String t) &nbsp;&nbsp;throws NumberFormatException, StringIndexOutOfBoundsException { &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">return Integer.parseInt(t.substring(0, t.indexOf(":"))); </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">}</span></p>
<p>In this case, we are saying that the getHours() method throws a NumberFormatException and a StringIndexOutOfBoundsException. If you wanted, you could even say:</p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">private static int getHours(String t) throws Exception { &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">return Integer.parseInt(t.substring(0, t.indexOf(":"))); </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">}</span></p>
<p>In our example, we're going to leave it as two specific exceptions (in class, we'll do it the other way), so that when we get them up to main(), we can differentiate between these exceptions and other exceptions that main() might throw.</p>
<p>The throws statement will cause any exceptions to be thrown up to the getTotalSeconds() method. We want them to go to main, so we have to include the throws clause in getTotalSeconds(), also:</p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">private static int getTotalSeconds(String t) &nbsp;&nbsp;throws NumberFormatException, StringIndexOutOfBoundsException { &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">return getHours(t) * 3600 + getMinutes(t) * 60 + getSeconds(t); </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">} </span></p>
<h4>Exercise</h4>
<p>Once these changes are made, you can add the try/catch block in your main() method. This should include a catch block for the errors from getTotalSeconds(). If these errors occur, it's because the user entered invalid data. Remind them of the valid format and exit the program so they can try it again.</p>
<p>Check your solution:</p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">public class UsingThrows { &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">public static void main(String[] args) &nbsp;{ &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">int totalSeconds=0; &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">try &nbsp;&nbsp;{ &nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">time = JOptionPane.showInputDialog(null, &nbsp;&nbsp;&nbsp;&nbsp;"Enter a time in the format hh:mm:ss", "Enter Time", &nbsp;&nbsp;&nbsp;&nbsp;JOptionPane.QUESTION_MESSAGE);&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">totalSeconds = getTotalSeconds(time); &nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">JOptionPane.showMessageDialog(null, "The time " + time + &nbsp;&nbsp;&nbsp;&nbsp;" in total seconds is " + totalSeconds, "Total Seconds", &nbsp;&nbsp;&nbsp;&nbsp;JOptionPane.INFORMATION_MESSAGE);</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">} &nbsp;&nbsp;catch (NumberFormatException ex) &nbsp;&nbsp;{ &nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">JOptionPane.showMessageDialog(null, &nbsp;&nbsp;&nbsp;&nbsp;"You entered an invalid time.\nPlease enter numbers only.", &nbsp;&nbsp;&nbsp;&nbsp;"Invalid Time",&nbsp;JOptionPane.ERROR_MESSAGE); &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">} &nbsp;&nbsp;catch (StringIndexOutOfBoundsException ex) &nbsp;&nbsp;{ &nbsp;&nbsp;&nbsp;</span></p>
<p style="padding-left: 120px;"><span style="font-family: courier new,courier;">JOptionPane.showMessageDialog(null, &nbsp;&nbsp;&nbsp;&nbsp;"You entered the time in the wrong format.\n" + &nbsp;&nbsp;&nbsp;&nbsp;"Please enter the time in the form hh:mm:ss", &nbsp;&nbsp;&nbsp;&nbsp;"Invalid Time", JOptionPane.ERROR_MESSAGE); &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">} &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} &nbsp; &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">private static int getTotalSeconds(String t) &nbsp;&nbsp;throws NumberFormatException, StringIndexOutOfBoundsException &nbsp;{ &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">return getHours(t) * 3600 + getMinutes(t) * 60 + getSeconds(t); &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">private static int getHours(String t) &nbsp;&nbsp;throws NumberFormatException, StringIndexOutOfBoundsException &nbsp;{ &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">return Integer.parseInt(t.substring(0, t.indexOf(":"))); &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">private static int getMinutes(String t) &nbsp;&nbsp;throws NumberFormatException, StringIndexOutOfBoundsException &nbsp;{ &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">return Integer.parseInt(t.substring(t.indexOf(":") + 1, t.lastIndexOf(":"))); &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">private static int getSeconds(String t) &nbsp;&nbsp;throws NumberFormatException, StringIndexOutOfBoundsException &nbsp;{ &nbsp;&nbsp;</span></p>
<p style="padding-left: 90px;"><span style="font-family: courier new,courier;">return Integer.parseInt(t.substring(t.lastIndexOf(":")+1)); &nbsp;</span></p>
<p style="padding-left: 60px;"><span style="font-family: courier new,courier;">} </span></p>
<p style="padding-left: 30px;"><span style="font-family: courier new,courier;">}</span></p>
<p>How would you modify this code so that the user is prompted repeatedly until they enter a valid value?</p>
<h3>When to use Exception Handlers</h3>
<h4>First, read chapter 13.7.</h4>
<p>Just because you have some code that might throw a catched exception does not mean you have to use a try-catch block to handle it! You will find that if you have a lot of code within try-catch blocks, your code will start to get messy and unstructured. If you can write validation code instead of using a try-catch block, you should do it!</p>
<p>As an example, you could create an isNumeric() method to check and see if a string can be parsed into a valid number, instead of using a try-catch block to catch a NumberFormatException.</p>
<p>When writing programs that read and write data to a file, it is most effective to perform the data validation when the data is being saved to the file. This ensures the integrity of the file itself, making sure that it doesn't contain any invalid data. In the program that saved records for the TFQuestion class to a file, what kind of data validation would be required and how would you code it?</p>
<p>Recall that there is some data validation inside the TFQuestion class itself - exceptions are thrown if the programmer tries to give an instance variable an invalid value. Other problems we should address include:</p>
<ul>
<li>Ensuring that the question ID is a valid numeric before attempting to set it.</li>
<li>Ensuring that the question's answer is a valid boolean before attempting to set it.</li>
<li>Ensuring that the guess passed into the isCorrect() method is a valid boolean.</li>
</ul>
<p>The ID can be handled using an isNumeric() method: get the ID from the user as a string, and if that string can be safely parsed into a numeric value, do so. We could do the same thing for the boolean value - we could write an isBoolean() method that checks to see if a string was equal to "true" or "false" before parsing it.</p>
<p>As you can see, you can handle many problems using code structures such as if-statements instead of using try-catch blocks. This is preferred, since try-catch blocks require more resources than simple if-statements (See Chapter 13.7)</p>
</body>
</html>